# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ytube_dl_proto_pb2 as ytube__dl__proto__pb2


class YoutubeDownloadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Download = channel.unary_unary(
                '/YoutubeDownload/Download',
                request_serializer=ytube__dl__proto__pb2.DownloadInfo.SerializeToString,
                response_deserializer=ytube__dl__proto__pb2.DownloadResult.FromString,
                )


class YoutubeDownloadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoutubeDownloadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Download': grpc.unary_unary_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=ytube__dl__proto__pb2.DownloadInfo.FromString,
                    response_serializer=ytube__dl__proto__pb2.DownloadResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YoutubeDownload', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YoutubeDownload(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YoutubeDownload/Download',
            ytube__dl__proto__pb2.DownloadInfo.SerializeToString,
            ytube__dl__proto__pb2.DownloadResult.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
