# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ytube_dl_proto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ytube_dl_proto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ytube_dl_proto.proto\"\x1b\n\x0c\x44ownloadInfo\x12\x0b\n\x03url\x18\x01 \x01(\t\" \n\x0e\x44ownloadResult\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32?\n\x0fYoutubeDownload\x12,\n\x08\x44ownload\x12\r.DownloadInfo\x1a\x0f.DownloadResult\"\x00\x62\x06proto3'
)




_DOWNLOADINFO = _descriptor.Descriptor(
  name='DownloadInfo',
  full_name='DownloadInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='DownloadInfo.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=51,
)


_DOWNLOADRESULT = _descriptor.Descriptor(
  name='DownloadResult',
  full_name='DownloadResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='DownloadResult.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['DownloadInfo'] = _DOWNLOADINFO
DESCRIPTOR.message_types_by_name['DownloadResult'] = _DOWNLOADRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DownloadInfo = _reflection.GeneratedProtocolMessageType('DownloadInfo', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADINFO,
  '__module__' : 'ytube_dl_proto_pb2'
  # @@protoc_insertion_point(class_scope:DownloadInfo)
  })
_sym_db.RegisterMessage(DownloadInfo)

DownloadResult = _reflection.GeneratedProtocolMessageType('DownloadResult', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADRESULT,
  '__module__' : 'ytube_dl_proto_pb2'
  # @@protoc_insertion_point(class_scope:DownloadResult)
  })
_sym_db.RegisterMessage(DownloadResult)



_YOUTUBEDOWNLOAD = _descriptor.ServiceDescriptor(
  name='YoutubeDownload',
  full_name='YoutubeDownload',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=87,
  serialized_end=150,
  methods=[
  _descriptor.MethodDescriptor(
    name='Download',
    full_name='YoutubeDownload.Download',
    index=0,
    containing_service=None,
    input_type=_DOWNLOADINFO,
    output_type=_DOWNLOADRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_YOUTUBEDOWNLOAD)

DESCRIPTOR.services_by_name['YoutubeDownload'] = _YOUTUBEDOWNLOAD

# @@protoc_insertion_point(module_scope)
